# Exported from Render on 2026-02-27T10:06:16Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: face-attendance-app
      runtime: python-3.11.9
      repo: https://github.com/GurpreetTech04/face-attendance-app
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: python app.py
      autoDeployTrigger: commit
